### ISSUE TITLE
FFT result different with kaldi SRFFT

### ISSUE THREAD

**Issue by mahuichao** [wenet-e2e/wekws#103]
Hello 
  I compared the result of **WeKws fft** and **kaldi srfft**, I found that the result is **different**,  could you tell me which method of **fft** do we used ?   the project is clean and light, I liked it!

Thanks

**Comment by robin1001** [comment]
Thanks. It's a simple and stupid FFT here, it may not be fast enough for mobile devices. We are going to replace it with better FFT in the future.

**Comment by mahuichao** [comment]
@robin1001  OK, I Got it, Thanks for your reply. Close issue.
