### ISSUE TITLE
AttributeError: 'MDTC' object has no attribute 'padding'

### ISSUE THREAD

**Issue by wangzhang1992** [wenet-e2e/wekws#104]
when i ran "examples/speechcommand_v1/s0/run.sh" step 4 , reported this error
![图片](https://user-images.githubusercontent.com/62131665/200206747-0e28ad84-8f50-4b12-869a-068253595dd9.png)

**Comment by wangzhang1992** [comment]
add cache error. tdc模型有padding 参数，但mdtc模型没有padding参数，但此处没有做判别，直接添加了model.backbone.padding。 是否要做一下框架判别再添加相应的padding?还是这块有其他想法？ 
![图片](https://user-images.githubusercontent.com/62131665/200208563-89ce10ef-9d80-4a94-964a-73e9b6bf56c4.png)

**Comment by mlxu995** [comment]
There is a bug in the mdtc backbone now, we will fix it in the next few days.

**Comment by wangzhang1992** [comment]
> 

ok！

**Comment by robin1001** [comment]
fixed, please see https://github.com/wenet-e2e/wekws/pull/105.

**Comment by wangzhang1992** [comment]
好的，谢谢！
