### ISSUE TITLE
GRU-based model?

### ISSUE THREAD

**Issue by nuance1979** [wenet-e2e/wekws#108]
I wonder why there isn't any GRU-based model implemented here.

Reading [your paper](http://lxie.nwpu-aslp.org/papers/2020ICASSP_HJY.pdf), especially Fig. 1-4, I have the impression that GRU-based model performed better than TCN-based counterpart. I understand that for production system there are more considerations/constraints (model size, FLOPS/energy, etc.) than just FAR/FRR. Just want to make sure I didn't miss anything.

**Comment by mlxu995** [comment]
As statement in the [paper ](http://lxie.nwpu-aslp.org/papers/2020ICASSP_HJY.pdf), the implementation of GRU-based model can be found in https://github.com/jingyonghou/KWS_Max-pooling_RHE 
But for the reason of production considerations/constraints, we now have no plan to support it in wekws.

**Comment by nuance1979** [comment]
Got it. May I ask what is the main reason that GRU-based model is not fit for production? Is it latency, computation/energy, model size, or something else?

**Comment by robin1001** [comment]
There is no special reason, we just do not implement it, and you can support GRU easily in the framework if GRU is required for your application.

**Comment by StuartIanNaylor** [comment]
I guess its down to destination more than anything as with many micro-controllers and npus recurrent layers often don't have support. I am not sure if tf4micro does or not now but say esp32 which the esp32-s3 could make a reasonable kws pretty sure it doesn't support lstm.
I haven't really worked out the model here but a CRNN has approx half the parameters of a DSCNN but the recurrent layers can be problematic on some platforms and also full int8 quantisation.

**Comment by nuance1979** [comment]
Thanks a lot @StuartIanNaylor ! That totally makes sense. However, I do see value in having a GRU-based model implemented here in WeKWS because, as you pointed out, it depends on where you want to use it for. If someone has a hardware where using a recurrent layer is not a problem, she/he would be happy to take the additional performance gain. In fact, if the gain is big enough, it might justify adding recurrent layer support to your hardware. But to make that decision, one has to know how big or small the gain is.

**Comment by StuartIanNaylor** [comment]
Is not the mdtc model recurrent? PS have you had a look at  https://github.com/google-research/google-research/tree/master/kws_streaming as its also a great KWS resource?

**Comment by robin1001** [comment]
Acctually, we have done some experiments before on GRU, and the result is not good, so we remove the impementation. please see https://github.com/wenet-e2e/wekws/tree/main/examples/hi_xiaowen/s0

![image](https://user-images.githubusercontent.com/6036624/204415655-2455aeb2-6503-4868-bb40-d158d683e6a0.png)

And there is also some investigation/model comparison in the literature, please see https://arxiv.org/pdf/1711.07128.pdf.

**Comment by StuartIanNaylor** [comment]
Yeah I think it was that model that kickstarted much as Arm then did a repo.

https://github.com/ARM-software/ML-KWS-for-MCU

Which kick started the extensive Google Research https://github.com/google-research/google-research/tree/master/kws_streaming which is incredibly extensive even includes some newer KWS such as

 [bc_resnet](https://github.com/google-research/google-research/blob/master/kws_streaming/models/bc_resnet.py)
 https://github.com/google-research/google-research/blob/master/kws_streaming/models/att_mh_rnn.py
 In fact to many to mention but very likely the key opensource resource on the internet for KWS.
 
 I haven't really worked out the model layers of MDTC yet and have a comparison

**Comment by nuance1979** [comment]
Thanks a lot @StuartIanNaylor and @robin1001 for the reference! I'll check them out.
