### ISSUE TITLE
Plotted DET Curve is empty

### ISSUE THREAD

**Issue by csetanmayjain** [wenet-e2e/wekws#113]
Hi,
I train a model on my custom dataset, with a single keyword.
Using compute_accuracy.py, I'm getting, 97% accuracy on the test dataset.

But when I tried to plot the DET curve using, `plot_det_curve.py`, the output DET curve image is empty. (Before running this, I already compute score.txt, and stats.txt)

Thanks

**Comment by robin1001** [comment]
please attach your score.txt and stats.txt.

**Comment by csetanmayjain** [comment]
Please find the attached score.txt, and stats.txt

[score.txt](https://github.com/wenet-e2e/wekws/files/10088606/score.txt)
[stats.0.txt](https://github.com/wenet-e2e/wekws/files/10088608/stats.0.txt)

Thanks

**Comment by mlxu995** [comment]
It seems that the FAR on your custom dataset is too large.
But you can also plot a DET curve by setting the xlim to a large value (such as --xlim 5000).
