### ISSUE TITLE
Finetuning support

### ISSUE THREAD

**Issue by csetanmayjain** [wenet-e2e/wekws#114]
Hi, 
Is there any way to train a KWS model, in case we want to train a new wake word model, without having much data?

Or can I finetune an existing model on the new wake word, which is trained on a good amount of data? If yes, how?

Thanks

**Comment by robin1001** [comment]
sorry, currently, here is no such method in our framework. We are investigation on the problem, and will try to figure out it in the future.

**Comment by csetanmayjain** [comment]
Okay, 
Thanks
