### ISSUE TITLE
How to prepare dataset for RIR & Musan Augmentation

### ISSUE THREAD

**Issue by csetanmayjain** [wenet-e2e/wekws#116]
Hi,
Would like know how to prepare dataset for RIR & Musan Augmentation
I go through the script, and understand that it needs data in `.mdb` format that should be inside `lmdb` folder. I have raw audio files, how to prepare data for it?
Also, would like to know, is there any flag in the configuration file, which I can use as a flag to apply augmentation or not.

Thanks

**Comment by robin1001** [comment]
please see https://github.com/wenet-e2e/wekws/blob/main/tools/make_lmdb.py

**Comment by mlxu995** [comment]
Just need preparing a wav.scp file and specify the path to save lmdb file. Then run "python make_lmdb.py /path/to/wav.scp /path/to/lmdb_dir" to prepare the lmdb file.
You can turn off augmentation by setting the corresponding probability to 0, or simply do not pass the corresponding lmdb file in run.sh

**Comment by csetanmayjain** [comment]
Thanks
