### ISSUE TITLE
Issue during testing while training with 80 Fbins hyperparameter

### ISSUE THREAD

**Issue by csetanmayjain** [wenet-e2e/wekws#118]
Hi,
I train a new model after changing Fbins to 80. The model trained successfully, but when I tried to test the model on some test cases, getting the following error:

`RuntimeError: The size of tensor a (80) must match the size of tensor b (40) at non-singleton dimension 2`

I just change the hyperparameter in conf file, apart from this, do we need to make change anywhere else in the code?
Is it something hard coded?

**Comment by mlxu995** [comment]
please make sure that the configs in testing are identical to that for training.

**Comment by csetanmayjain** [comment]
those are the same only
even I'm taking the configuration from training only for testing

**Comment by mlxu995** [comment]
It sees that the cmvn used for testing is not identical to the one used for training. If you changed the work dir and the cmvn file?

**Comment by csetanmayjain** [comment]
I didn't make any changes in the directory

**Comment by mlxu995** [comment]
I trained a model that also set Fbins to 80.  It seems nothing abnormal when testing it.
Could you make a new work dir and re-run the script from stage 0.

**Comment by csetanmayjain** [comment]
sure, I will give it a try again
