### ISSUE TITLE
Error while applying RIRS augmentation

### ISSUE THREAD

**Issue by csetanmayjain** [wenet-e2e/wekws#126]
I'm getting following error, while applying RIRS augmentation on my training dataset.
`ValueError: volume and kernel should have the same dimensionality`

I downloaded the RIRS dataset, process it, and created lmdb file succesfully, during training I'm getting that issue.

**Comment by mlxu995** [comment]
it seems that some of the rir files you used is two channels. you should only use mono rir files.

**Comment by csetanmayjain** [comment]
I downloaded the RIRS data, extract it, and use it directly.
Do we need to filter the RIRS data before creating lmdb?

**Comment by mlxu995** [comment]
It depends on which data you download, some open-source RIRS data set contains both mono and multichannel rirs.
