### ISSUE TITLE
 conda install 报错

### ISSUE THREAD

**Issue by suyulin** [wenet-e2e/wekws#137]
执行命令
``` 
$ conda install pytorch=1.10.0 torchaudio=0.10.0 cudatoolkit=11.1 -c pytorch -c conda-forge
```
提示：`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`

**Comment by mlxu995** [comment]
You can try this: conda install pytorch=1.13.0 torchaudio=0.13.0 cudatoolkit=11.1 -c pytorch 
-c nvidia
