### ISSUE TITLE
使用 wenet::WavReader 初始化一个wav文件报错

### ISSUE THREAD

**Issue by HonglinChu** [wenet-e2e/wekws#139]
你好，在linux电脑上编译通过onnxruntime项目文件，生成kws_main可执行文件，我自己录制了一段17s的录音（采样率16000）
当运行kws_main的时候，加载wav报错，header中的num_channel_，sample_rate 全部是0

![image](https://github.com/wenet-e2e/wekws/assets/11087575/3ba09a91-ed40-44ec-91ba-e58a06ed5b9c)

![image](https://github.com/wenet-e2e/wekws/assets/11087575/9f6c6f12-a270-4dd6-93dc-00980c9c13fd)

**Comment by mlxu995** [comment]
录音的音频格式正确吗，需要16位，采样率16k的单通道音频

**Comment by HonglinChu** [comment]
[xiaowen.zip](https://github.com/wenet-e2e/wekws/files/12387286/xiaowen.zip)
我自己用手机录制的wav文件，16kHz采样
