### ISSUE TITLE
missing token_file and lexicon_file

### ISSUE THREAD

**Issue by HonglinChu** [wenet-e2e/wekws#140]
Hi, thanks for your work, when i run wekws/bin/stream_kws_ctc.py，mising token_file  and lexicon_file, could you provide a 
example?
![image](https://github.com/wenet-e2e/wekws/assets/11087575/29410c0a-bb0d-4d8a-98ea-69bae1aca877)

**Comment by mlxu995** [comment]
you can find the files [here](https://www.modelscope.cn/studios/thuduj12/KWS_Nihao_Xiaojing/files)

**Comment by HonglinChu** [comment]
Thank you
