### ISSUE TITLE
fsmn_ctc模型导出onnx时报错！

### ISSUE THREAD

**Issue by Dapannnnn** [wenet-e2e/wekws#143]
**Describe the bug**
当我运行run_fsmn_ctc.sh来训练时，前面地流程一切正常，当运行至第四阶段，导出onnx模型时报错：
![image](https://github.com/wenet-e2e/wekws/assets/86400961/7fba3dc7-c172-4349-8f92-e7a382f2ce0c)

结合报错信息似乎是cache的设置不对，但我不知道如何正确的设置。

**Comment by mlxu995** [comment]
可以提供一下 fsmn 的模型吗

**Comment by Dapannnnn** [comment]
> 

我也是这样

**Comment by Dapannnnn** [comment]
我debug了以下，发现是cache这个输入设置的有问题。得根据fsmn模型对cache的要求设置输入。不过我还没有仔细研究。

**Comment by mlxu995** [comment]
已修复，请参考 #146

**Comment by LAM037** [comment]
> 已修复，请参考 #146

多谢大佬，确实是可以了。下面的输出就是提到的精度问题吗？
Export to onnx succeed, but pytorch/onnx have different
                 outputs when given the same input, please check!!!

**Comment by mlxu995** [comment]
> > 已修复，请参考 #146
> 
> 多谢大佬，确实是可以了。下面的输出就是提到的精度问题吗？ Export to onnx succeed, but pytorch/onnx have different outputs when given the same input, please check!!!

是的，我打印了对比了torch和onnx各自的cache，发现绝对值比较大，所以也不确定这个精度损失是不是可接受。
