### ISSUE TITLE
run_fsmn_ctc.sh在训练过程中，加载base.pt爆出问题

### ISSUE THREAD

**Issue by Theweekfoolish229** [wenet-e2e/wekws#144]
您好：
我在训练hi_xiaowen中，运行run_fsmn_ctc.sh，发现在训练阶段（stage 1）的时候，git下base模型，在价值checkpoint的时候，爆出如下问题：
<img width="1473" alt="image" src="https://github.com/wenet-e2e/wekws/assets/53725404/8bd80882-b3e5-4f4c-aabf-d679d836ee90">

**Comment by lin-xiaosheng** [comment]
你好，我也遇到了相同的问题，这困扰了我很久，我尝试了很多办法都没有能解决。你能告诉我您当初是怎么解决的吗，这对我非常重要！

**Comment by ZJS007** [comment]
您好，请问怎么解决的呢？
