### ISSUE TITLE
run_fsmn_ctc.sh num_keywords

### ISSUE THREAD

**Issue by kismeter** [wenet-e2e/wekws#157]
Hello, in run_fsmn_ctc.sh the num_keywords=2599, why set this value? In run.sh this value is 2.

**Comment by mlxu995** [comment]
In the first script, 2599 is the number of tokens used in training ctc. The name of the variable is not particularly appropriate and may lead to misunderstandings.
In the second, 2 is the number of the real keywords (i.e. "你好问问" and "嗨小问")
