### ISSUE TITLE
Questions about optimizer.zero_grad()

### ISSUE THREAD

**Issue by chmod740** [wenet-e2e/wekws#72]
Hello, this repository is a very amazing project about KWS. 
When I was reading the source code, I noticed that in the training stage, when optimizer.step() is called, optimizer.zero_grad() is not called, there are some differences with other projects I've seen before, and I'm wondering if this is a special trick or some other reason.
I'm very much looking forward to your reply.

**Comment by robin1001** [comment]
It's a bug, could you help to make a PR to fix the problem.
