### ISSUE TITLE
Android can not build to release apk

### ISSUE THREAD

**Issue by wjyfelicity** [wenet-e2e/wekws#85]

**Comment by robin1001** [comment]
Any log or error message?

**Comment by pengzhendong** [comment]
Have you convert the onnx model to ort format, and put it into assets folder?

**Comment by wjyfelicity** [comment]
> 

I put final.zip and words.txt into assets folder.

**Comment by wjyfelicity** [comment]
> Any log or error message?

![WXWorkCapture_16627089341220](https://user-images.githubusercontent.com/24841439/189297155-d1004cfe-06ba-4d13-a7c4-0c0552469d06.png)

**Comment by wjyfelicity** [comment]
> Have you convert the onnx model to ort format, and put it into assets folder?

I put final.zip and words.txt into assets folder.

**Comment by pengzhendong** [comment]
Only support `ort` format model. And plz rename it to `wenwen.ort`.

**Comment by wjyfelicity** [comment]
> 



> Only support `ort` format model. And plz rename it to `wenwen.ort`.

ok, I try it right now.
