### ISSUE TITLE
when mdtc add cache? 

### ISSUE THREAD

**Issue by jldeng3** [wenet-e2e/wekws#86]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by robin1001** [comment]
We do not have band width to do it recently. Are you interested in it? Welcome to contribution.

**Comment by mlxu995** [comment]
We have added cache in mdtc, please see https://github.com/wenet-e2e/wekws/pull/105.
