### ISSUE TITLE
ds_tcn parameter count incorrect?

### ISSUE THREAD

**Issue by sugarcase** [wenet-e2e/wekws#95]
![image](https://user-images.githubusercontent.com/23147096/191412806-bab24f6b-5699-4609-bcc4-f779bc6c720b.png)

2022-09-21 12:14:09,323 WARNING the number of model params: 287490
according to log, it's about 287K

**Comment by robin1001** [comment]
Good catch! We forget to change to parameters after we change the config. Could you help to make a  PR to fix the problem?

**Comment by sugarcase** [comment]
> 

OK，I will make a PR later.
